FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    bluez \
    python3 \
    python3-pip \
    python3-venv \
    python3-gi \
    python3-dbus \
    dbus \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt

COPY . .
ENV PYTHONPATH=/app

# Start dbus and bluetoothd
CMD service dbus start && \
    bluetoothd --nodetach --debug &  \
    sleep 2 && \
    python3 rpi_ble/main.py